services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      DB_URL: jdbc:postgresql://db:5432/azerty-db-local
      DB_USER: postgres
      DB_PASSWORD: mot_de_passe

  db:
    image: postgres:14
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: azerty-db-local
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mot_de_passe
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: