spring:
  application:
    name: azerty-api
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
security:
  jwt:
    secret-key: ${JWT_SECRET_KEY}
    expiration-time: 3600000